### ISSUE TITLE
没有找到database schema

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg-showcase-aliyun-blog#1]
没有找到database schema

**Comment by atian25** [comment]
@jtyjty99999 fix 后顺便把这个仓库的 issue 从 settings 里面关掉, 统一在 egg 那边.

**Comment by jtyjty99999** [comment]
@zhoudaqing 这个仓库我还在完善，稍安勿躁

**Comment by atian25** [comment]
统一到 egg 那边交流
